[project]
name = "ai-chat-bill"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "chainlit>=1.1.402",
    "langchain>=0.2.12",
    "langchain-openai>=0.1.22",
    "openai>=1.37.0",
]
